/*
 * ============================================================================
 *  ARTWORK DATA — single source of truth for the whole site.
 * ============================================================================
 *
 *  To ADD a piece:    copy a block below, give it a unique `id`, fill it in.
 *  To REMOVE a piece: delete its block.
 *  To EDIT a piece:   change the fields in its block.
 *
 *  Field reference:
 *    id          unique slug, used in the URL (piece.html?id=THIS). No spaces.
 *    title       display name of the piece.
 *    year        the year the piece was made (shown on the detail page).
 *    medium      e.g. "Oil on Canvas", "Soft and Oil Pastel on Paper".
 *    size        the real-world size label, e.g. "12 × 14 in". May be ""
 *                (empty) — the detail page hides the size row when it is.
 *    realW/realH the real-world size in INCHES, used by the "True scale"
 *                gallery view to size every piece relative to the others.
 *                Derived from `size` but kept to the photo's true shape; for
 *                pieces with no catalogued size these are best guesses
 *                (flagged inline). Edit these to fine-tune the scale wall.
 *    width/height  the IMAGE's pixel dimensions. They set each tile's aspect
 *                  ratio in the gallery so the frame matches the photo exactly
 *                  (no odd cropping). The human-readable inch size lives in
 *                  `size`, above.
 *    image       full-size image (shown on the dedicated piece page).
 *    thumb       small image used on the homepage wall (loads fast).
 *    description longer text shown on the dedicated page. Optional — leave
 *                "" and the detail page omits the paragraph.
 *
 *  Images live in assets/art/ (full) and assets/art/thumbs/ (small).
 * ============================================================================
 */

const ARTWORKS = [
  {
    id: "1body2body3body4",
    title: "1Body2Body3Body4",
    year: 2025,
    medium: "Acrylic on vinyl wallpaper",
    size: "30 × 50 in",
    realW: 32.5, realH: 50,
    width: 1300, height: 2000,
    image: "assets/art/1body2body3body4.jpg",
    thumb: "assets/art/thumbs/1body2body3body4.jpg",
    description: "",
  },
  {
    id: "three",
    title: "Three",
    year: 2026,
    medium: "Soft and Oil Pastel on paper",
    size: "",
    realW: 18, realH: 13,   // size unknown — best-guess inches
    width: 2000, height: 1449,
    image: "assets/art/three.jpg",
    thumb: "assets/art/thumbs/three.jpg",
    description: "",
  },
  {
    id: "a-love-supreme",
    title: "A Love Supreme",
    year: 2025,
    medium: "Oil on Canvas",
    size: "12 × 14 in",
    realW: 14, realH: 10.9,
    width: 2000, height: 1557,
    image: "assets/art/a-love-supreme.jpg",
    thumb: "assets/art/thumbs/a-love-supreme.jpg",
    description: "",
  },
  {
    id: "a-pilgrimage-of-sorts",
    title: "A pilgrimage of sorts",
    year: 2026,
    medium: "Oil on Canvas",
    size: "20 × 16 in",
    realW: 16, realH: 20,
    width: 1600, height: 2000,
    image: "assets/art/a-pilgrimage-of-sorts.jpg",
    thumb: "assets/art/thumbs/a-pilgrimage-of-sorts.jpg",
    description: "",
  },
  {
    id: "apple-field",
    title: "Apple Field",
    year: 2025,
    medium: "Oil on Canvas",
    size: "12 × 16 in",
    realW: 16, realH: 11.9,
    width: 2000, height: 1483,
    image: "assets/art/apple-field.jpg",
    thumb: "assets/art/thumbs/apple-field.jpg",
    description: "",
  },
  {
    id: "before-we-knew-we-were-naked",
    title: "Before We Knew We Were Naked",
    year: 2024,
    medium: "Oil Pastel on Concrete Subfloor",
    size: "53 × 37 in",
    realW: 53, realH: 36.4,
    width: 2000, height: 1372,
    image: "assets/art/before-we-knew-we-were-naked.jpg",
    thumb: "assets/art/thumbs/before-we-knew-we-were-naked.jpg",
    description: "",
  },
  {
    id: "blues",
    title: "Blues",
    year: 2024,
    medium: "Oil on Canvas",
    size: "12 × 9 in",
    realW: 9, realH: 12,
    width: 1500, height: 2000,
    image: "assets/art/blues.jpg",
    thumb: "assets/art/thumbs/blues.jpg",
    description: "",
  },
  {
    id: "camping-with-meg",
    title: "Camping With Meg",
    year: 2025,
    medium: "Acrylic on Paper",
    size: "45 × 55 in",
    realW: 55, realH: 44.6,
    width: 2000, height: 1620,
    image: "assets/art/camping-with-meg.jpg",
    thumb: "assets/art/thumbs/camping-with-meg.jpg",
    description: "",
  },
  {
    id: "christmas-2023-father",
    title: "Christmas 2023/Father",
    year: 2023,
    medium: "Oil on Canvas",
    size: "12 × 14 in",
    realW: 10.5, realH: 14,
    width: 1493, height: 2000,
    image: "assets/art/christmas-2023-father.jpg",
    thumb: "assets/art/thumbs/christmas-2023-father.jpg",
    description: "",
  },
  {
    id: "couldnt-his-tears-of-repentance-be-real",
    title: "Couldn't his Tears of Repentance be Real?",
    year: 2026,
    medium: "Oil on Canvas",
    size: "24 × 48 in",
    realW: 24, realH: 48,
    width: 1000, height: 2000,
    image: "assets/art/couldnt-his-tears-of-repentance-be-real.jpg",
    thumb: "assets/art/thumbs/couldnt-his-tears-of-repentance-be-real.jpg",
    description: "",
  },
  {
    id: "dance-vicki",
    title: "DANCE VICKI!",
    year: 2025,
    medium: "soft pastel on paper",
    size: "",
    realW: 18, realH: 24,   // size unknown — best-guess inches
    width: 1500, height: 2000,
    image: "assets/art/dance-vicki.jpg",
    thumb: "assets/art/thumbs/dance-vicki.jpg",
    description: "",
  },
  {
    id: "deathly-awe",
    title: "Deathly Awe",
    year: 2025,
    medium: "Oil Pastel on paper",
    size: "45 × 55 in",
    realW: 55, realH: 49.6,
    width: 2000, height: 1803,
    image: "assets/art/deathly-awe.jpg",
    thumb: "assets/art/thumbs/deathly-awe.jpg",
    description: "",
  },
  {
    id: "duncans-flowers",
    title: "Duncan's Flowers",
    year: 2023,
    medium: "Acrylic on Canvas",
    size: "20 × 16 in",
    realW: 16.6, realH: 20,
    width: 1662, height: 2000,
    image: "assets/art/duncans-flowers.jpg",
    thumb: "assets/art/thumbs/duncans-flowers.jpg",
    description: "",
  },
  {
    id: "ethan",
    title: "Ethan",
    year: 2024,
    medium: "Graphite on paper",
    size: "24 × 18 in",
    realW: 24, realH: 16.9,
    width: 2000, height: 1408,
    image: "assets/art/ethan.jpg",
    thumb: "assets/art/thumbs/ethan.jpg",
    description: "",
  },
  {
    id: "fairport-kitchen",
    title: "Fairport Kitchen",
    year: 2026,
    medium: "Oil on Canvas",
    size: "24 × 24 in",
    realW: 23.8, realH: 24,
    width: 1983, height: 2000,
    image: "assets/art/fairport-kitchen.jpg",
    thumb: "assets/art/thumbs/fairport-kitchen.jpg",
    description: "",
  },
  {
    id: "genesis-1-2-3",
    title: "Genesis 1:2-3",
    year: 2026,
    medium: "Oil on Canvas",
    size: "20 × 16 in",
    realW: 16, realH: 20,
    width: 1600, height: 2000,
    image: "assets/art/genesis-1-2-3.jpg",
    thumb: "assets/art/thumbs/genesis-1-2-3.jpg",
    description: "",
  },
  {
    id: "guard",
    title: "Guard",
    year: 2024,
    medium: "Oil Pastel on Fabric and Plywood",
    size: "24 × 24 in",
    realW: 24, realH: 21,
    width: 2000, height: 1753,
    image: "assets/art/guard.jpg",
    thumb: "assets/art/thumbs/guard.jpg",
    description: "",
  },
  {
    id: "house-of-numpties",
    title: "House of Numpties",
    year: 2024,
    medium: "Acrylic on Canvas",
    size: "24 × 24 in",
    realW: 23.9, realH: 24,
    width: 1990, height: 2000,
    image: "assets/art/house-of-numpties.jpg",
    thumb: "assets/art/thumbs/house-of-numpties.jpg",
    description: "",
  },
  {
    id: "i-wonder",
    title: "I Wonder",
    year: 2025,
    medium: "Oil Pastel on board",
    size: "12 × 12 in",
    realW: 12, realH: 12,
    width: 1992, height: 2000,
    image: "assets/art/i-wonder.jpg",
    thumb: "assets/art/thumbs/i-wonder.jpg",
    description: "",
  },
  {
    id: "im-sorry-i-hurt-you-i-dont-know-how-to-do-this",
    title: "I’m sorry I hurt you, I don’t know how to do this",
    year: 2025,
    medium: "Soft and Oil Pastel on Plywood",
    size: "21 × 10 in",
    realW: 9.5, realH: 21,
    width: 905, height: 2000,
    image: "assets/art/im-sorry-i-hurt-you-i-dont-know-how-to-do-this.jpg",
    thumb: "assets/art/thumbs/im-sorry-i-hurt-you-i-dont-know-how-to-do-this.jpg",
    description: "",
  },
  {
    id: "johns-cat",
    title: "John's Cat",
    year: 2024,
    medium: "Oil Pastel On Paper",
    size: "",
    realW: 12, realH: 16,   // size unknown — best-guess inches
    width: 1500, height: 2000,
    image: "assets/art/johns-cat.jpg",
    thumb: "assets/art/thumbs/johns-cat.jpg",
    description: "",
  },
  {
    id: "matisse-study-1",
    title: "Matisse Study #1",
    year: 2026,
    medium: "Oil on Canvas",
    size: "16 × 12 in",
    realW: 11.9, realH: 16,
    width: 1484, height: 2000,
    image: "assets/art/matisse-study-1.jpg",
    thumb: "assets/art/thumbs/matisse-study-1.jpg",
    description: "",
  },
  {
    id: "matisse-study-2",
    title: "Matisse Study #2",
    year: 2026,
    medium: "Oil on Canvas",
    size: "12 × 12 in",
    realW: 12, realH: 12,
    width: 2000, height: 1996,
    image: "assets/art/matisse-study-2.jpg",
    thumb: "assets/art/thumbs/matisse-study-2.jpg",
    description: "",
  },
  {
    id: "momma",
    title: "Momma",
    year: 2025,
    medium: "Soft and Oil Pastel on Paper",
    size: "",
    realW: 18.1, realH: 24,   // size unknown — best-guess inches
    width: 1511, height: 2000,
    image: "assets/art/momma.jpg",
    thumb: "assets/art/thumbs/momma.jpg",
    description: "",
  },
  {
    id: "morning-stretch",
    title: "Morning Stretch",
    year: 2025,
    medium: "Oil Pastel on Fabric and Plywood",
    size: "48 × 32 in",
    realW: 48, realH: 32.7,
    width: 2000, height: 1362,
    image: "assets/art/morning-stretch.jpg",
    thumb: "assets/art/thumbs/morning-stretch.jpg",
    description: "",
  },
  {
    id: "portrait",
    title: "Portrait",
    year: 2023,
    medium: "Acrylic on Canvas",
    size: "20 × 16 in",
    realW: 20, realH: 20,
    width: 2000, height: 2000,
    image: "assets/art/portrait.jpg",
    thumb: "assets/art/thumbs/portrait.jpg",
    description: "",
  },
  {
    id: "sad-and-alien",
    title: "Sad and Alien",
    year: 2024,
    medium: "Oil on Canvas",
    size: "12 × 9 in",
    realW: 8.5, realH: 12,
    width: 1414, height: 2000,
    image: "assets/art/sad-and-alien.jpg",
    thumb: "assets/art/thumbs/sad-and-alien.jpg",
    description: "",
  },
  {
    id: "separator",
    title: "Separator",
    year: 2025,
    medium: "Soft and Oil Pastel on Plywood",
    size: "23 × 20 in",
    realW: 21.2, realH: 23,
    width: 1843, height: 2000,
    image: "assets/art/separator.jpg",
    thumb: "assets/art/thumbs/separator.jpg",
    description: "",
  },
  {
    id: "sick-angry-otherwise-egregious",
    title: "Sick, Angry, otherwise Egregious",
    year: 2026,
    medium: "Oil on Canvas",
    size: "20 × 16 in",
    realW: 20, realH: 16,
    width: 2000, height: 1600,
    image: "assets/art/sick-angry-otherwise-egregious.jpg",
    thumb: "assets/art/thumbs/sick-angry-otherwise-egregious.jpg",
    description: "",
  },
  {
    id: "sir-is-this-real",
    title: "Sir, is this real?",
    year: 2025,
    medium: "Oil on Canvas",
    size: "12 × 9 in",
    realW: 9, realH: 12,
    width: 1500, height: 2000,
    image: "assets/art/sir-is-this-real.jpg",
    thumb: "assets/art/thumbs/sir-is-this-real.jpg",
    description: "",
  },
  {
    id: "sit-spot",
    title: "Sit Spot",
    year: 2025,
    medium: "Oil on Canvas",
    size: "12 × 14 in",
    realW: 14, realH: 10.8,
    width: 2000, height: 1536,
    image: "assets/art/sit-spot.jpg",
    thumb: "assets/art/thumbs/sit-spot.jpg",
    description: "",
  },
  {
    id: "something-warm-and-sweet",
    title: "Something Warm and Sweet",
    year: 2026,
    medium: "Oil on Canvas",
    size: "22 × 16 in",
    realW: 22, realH: 17.6,
    width: 2000, height: 1604,
    image: "assets/art/something-warm-and-sweet.jpg",
    thumb: "assets/art/thumbs/something-warm-and-sweet.jpg",
    description: "",
  },
  {
    id: "stained-lips",
    title: "Stained Lips",
    year: 2025,
    medium: "Soft and Oil Pastel on Plywood",
    size: "",
    realW: 18.6, realH: 24,   // size unknown — best-guess inches
    width: 1553, height: 2000,
    image: "assets/art/stained-lips.jpg",
    thumb: "assets/art/thumbs/stained-lips.jpg",
    description: "",
  },
  {
    id: "that-sweet-but-far-off-sound-that-hails-a-new-creation",
    title: "That Sweet but far off sound that hails a new creation",
    year: 2026,
    medium: "Oil on Canvas",
    size: "20 × 16 in",
    realW: 16, realH: 20,
    width: 1600, height: 2000,
    image: "assets/art/that-sweet-but-far-off-sound-that-hails-a-new-creation.jpg",
    thumb: "assets/art/thumbs/that-sweet-but-far-off-sound-that-hails-a-new-creation.jpg",
    description: "",
  },
  {
    id: "that-tree-to-be-alone-with-me",
    title: "That Tree to be Alone With Me",
    year: 2026,
    medium: "Oil on Canvas",
    size: "12 × 16 in",
    realW: 16, realH: 12,
    width: 2000, height: 1501,
    image: "assets/art/that-tree-to-be-alone-with-me.jpg",
    thumb: "assets/art/thumbs/that-tree-to-be-alone-with-me.jpg",
    description: "",
  },
  {
    id: "that-tree-across-from-me",
    title: "That Tree Across From Me",
    year: 2025,
    medium: "Soft Pastel on Paper",
    size: "",
    realW: 13, realH: 24,   // size unknown — best-guess inches
    width: 1086, height: 2000,
    image: "assets/art/that-tree-across-from-me.jpg",
    thumb: "assets/art/thumbs/that-tree-across-from-me.jpg",
    description: "",
  },
  {
    id: "the-heart-of-man-is-impossible-to-hold-19-26",
    title: "The Heart of Man is Impossible to Hold/19:26",
    year: 2026,
    medium: "Oil on Drywall",
    size: "45 × 24 in",
    realW: 23.6, realH: 45,
    width: 1048, height: 2000,
    image: "assets/art/the-heart-of-man-is-impossible-to-hold-19-26.jpg",
    thumb: "assets/art/thumbs/the-heart-of-man-is-impossible-to-hold-19-26.jpg",
    description: "",
  },
  {
    id: "the-preachers-house",
    title: "The Preachers House",
    year: 2025,
    medium: "Oil on Canvas",
    size: "",
    realW: 18, realH: 24,   // size unknown — best-guess inches
    width: 1501, height: 2000,
    image: "assets/art/the-preachers-house.jpg",
    thumb: "assets/art/thumbs/the-preachers-house.jpg",
    description: "",
  },
  {
    id: "they-arrived",
    title: "They Arrived",
    year: 2025,
    medium: "Oil on Canvas",
    size: "20 × 16 in",
    realW: 16, realH: 20,
    width: 1597, height: 2000,
    image: "assets/art/they-arrived.jpg",
    thumb: "assets/art/thumbs/they-arrived.jpg",
    description: "",
  },
  {
    id: "things-you-give-up",
    title: "Things You Give Up",
    year: 2025,
    medium: "Soft Pastel on Paper",
    size: "5 × 7 in",
    realW: 4.8, realH: 7,
    width: 1383, height: 2000,
    image: "assets/art/things-you-give-up.jpg",
    thumb: "assets/art/thumbs/things-you-give-up.jpg",
    description: "",
  },
  {
    id: "untitled-1",
    title: "Untitled #1",
    year: 2024,
    medium: "Acrylic and Oil Pastel on Paper",
    size: "45 × 55 in",
    realW: 55, realH: 42.2,
    width: 2000, height: 1533,
    image: "assets/art/untitled-1.jpg",
    thumb: "assets/art/thumbs/untitled-1.jpg",
    description: "",
  },
  {
    id: "untitled-2",
    title: "Untitled #2",
    year: 2026,
    medium: "Oil on Canvas",
    size: "12 × 9 in",
    realW: 9.1, realH: 12,
    width: 1513, height: 2000,
    image: "assets/art/untitled-2.jpg",
    thumb: "assets/art/thumbs/untitled-2.jpg",
    description: "",
  },
  {
    id: "untitled-3",
    title: "Untitled #3",
    year: 2023,
    medium: "Oil Pastel on Canvas",
    size: "12 × 16 in",
    realW: 16, realH: 12.2,
    width: 2000, height: 1526,
    image: "assets/art/untitled-3.jpg",
    thumb: "assets/art/thumbs/untitled-3.jpg",
    description: "",
  },
  {
    id: "untitled-4",
    title: "Untitled #4",
    year: 2026,
    medium: "Oil on Canvas",
    size: "24 × 18 in",
    realW: 18, realH: 24,
    width: 1500, height: 2000,
    image: "assets/art/untitled-4.jpg",
    thumb: "assets/art/thumbs/untitled-4.jpg",
    description: "",
  },
  {
    id: "untitled-5",
    title: "Untitled #5",
    year: 2026,
    medium: "Oil on Canvas",
    size: "20 × 16 in",
    realW: 16, realH: 20,
    width: 1600, height: 2000,
    image: "assets/art/untitled-5.jpg",
    thumb: "assets/art/thumbs/untitled-5.jpg",
    description: "",
  },
  {
    id: "untitled-6",
    title: "Untitled #6",
    year: 2025,
    medium: "Oil on Canvas",
    size: "24 × 18 in",
    realW: 18, realH: 24,
    width: 1500, height: 2000,
    image: "assets/art/untitled-6.jpg",
    thumb: "assets/art/thumbs/untitled-6.jpg",
    description: "",
  },
  {
    id: "untitled-7",
    title: "Untitled #7",
    year: 2026,
    medium: "Oil on Canvas",
    size: "12 × 9 in",
    realW: 12, realH: 8.9,
    width: 2000, height: 1484,
    image: "assets/art/untitled-7.jpg",
    thumb: "assets/art/thumbs/untitled-7.jpg",
    description: "",
  },
  {
    id: "untitled-8",
    title: "Untitled #8",
    year: 2025,
    medium: "Oil Pastel on board",
    size: "21 × 19 in",
    realW: 18.9, realH: 21,
    width: 1803, height: 2000,
    image: "assets/art/untitled-8.jpg",
    thumb: "assets/art/thumbs/untitled-8.jpg",
    description: "",
  },
  {
    id: "untitled-9",
    title: "Untitled #9",
    year: 2026,
    medium: "Oil on Canvas",
    size: "9 × 12 in",
    realW: 12, realH: 9,
    width: 2000, height: 1494,
    image: "assets/art/untitled-9.jpg",
    thumb: "assets/art/thumbs/untitled-9.jpg",
    description: "",
  },
  {
    id: "where-two-or-more-gathered",
    title: "Where Two or More Gathered",
    year: 2025,
    medium: "Acrylic and Oil Pastel on Paper",
    size: "55 × 55 in",
    realW: 49.4, realH: 55,
    width: 1796, height: 2000,
    image: "assets/art/where-two-or-more-gathered.jpg",
    thumb: "assets/art/thumbs/where-two-or-more-gathered.jpg",
    description: "",
  },
  {
    id: "yarah",
    title: "Yarah",
    year: 2026,
    medium: "Oil on Canvas",
    size: "12 × 16 in",
    realW: 16, realH: 12,
    width: 2000, height: 1500,
    image: "assets/art/yarah.jpg",
    thumb: "assets/art/thumbs/yarah.jpg",
    description: "",
  },
  {
    id: "you-cant-stay-here",
    title: "You Cant Stay Here",
    year: 2026,
    medium: "Oil on Canvas",
    size: "20 × 16 in",
    realW: 16, realH: 20,
    width: 1600, height: 2000,
    image: "assets/art/you-cant-stay-here.jpg",
    thumb: "assets/art/thumbs/you-cant-stay-here.jpg",
    description: "",
  },
];

// Make the data available to the page scripts (and ignore in non-browser ctx).
if (typeof window !== "undefined") {
  window.ARTWORKS = ARTWORKS;
}
